# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.TextField(max_length='40'),
        ),
    ]
