# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=pyuploadcare.dj.models.ImageField(default=True),
        ),
    ]
