# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181008_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=pyuploadcare.dj.models.ImageField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=pyuploadcare.dj.models.ImageField(),
        ),
    ]
