# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20181009_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_caption',
            field=models.TextField(max_length='300'),
        ),
    ]
